### ISSUE TITLE
add back/change `/get` for retrieving Animusic videos

### ISSUE THREAD

**Issue by jamesa08** [sunset-developer/GrooveBot#13]
`.get` was the old way of retrieving music, and it has been renamed to `/whatis`. This is quite confusing for returning users who want to quickly jump to Animusic content. 

`/get` and `/whatis` should both be aliases for the same command to reduce confusion, or rename `/whatis` to `/get`.

**Comment by sunset-developer** [comment]
Pushed an update with alias, thanks.
